M48
; DRILL file {KiCad 7.0.11} date Tue Nov 26 16:26:30 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-26T16:26:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.1791Y-4.0079
X4.1791Y-4.1811
T2
X5.1117Y-4.3504
X5.1117Y-4.7047
T3
X4.1339Y-2.1654
X4.1339Y-4.9213
X7.6772Y-2.1654
X7.6772Y-4.9213
M30
